 # Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RxSwiftSimple' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for RxSwiftSimple
    pod 'RxSwift', '~> 5.0.0'
    pod 'RxCocoa', '~> 5.0.0'
    pod 'SnapKit', '~> 5.0.0'
    pod 'NVActivityIndicatorView', '~> 4.7.0'

end
